# Site
title:              'Weiming Hu'
bio:                ''
description:        "I'm a Ph.D. candidate at Penn State University with a research interest in Geoscience, Computational Algorithm, and High-Performance Computing."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://weiming-hu.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   weiming-hu

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-116139459-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:              weiming.pennstate@outlook.com
#twitter:            username
facebook:           gavin.hu.9887
github-url:         https://github.com/Weiming-Hu
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           weiming-hu-607995117
#xing:              username
#instagram:         username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# In need of
# nextcloud
# researchgate
# candyjar
# gitlab

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
